export default {
  id: "catppuccin-latte",
  name: "Catppuccin Latte",
  aliases: ["catppuccin"],
  appearance: "light",
  description: "A creamy light adaptation with lavender-blue interactions.",
  source: {
    name: "Catppuccin Palette",
    url: "https://github.com/catppuccin/palette",
    revision: "v1.8.0",
    license: "MIT",
  },
  colors: {
    canvas: "#eff1f5",
    surface: "#ffffff",
    surfaceRaised: "#ffffff",
    text: "#4c4f69",
    textMuted: "#6c6f85",
    border: "#bcc0cc",
    primary: "#1e66f5",
    primaryText: "#ffffff",
    focus: "#1e66f5",
    selection: "#c6d0f5",
    selectionText: "#303446",
    codeBackground: "#e6e9ef",
  },
  typography: {
    sans: "Inter, ui-sans-serif, system-ui, sans-serif",
    mono: '"Fira Code", ui-monospace, monospace',
  },
  rhythm: {
    lineHeight: 1.55,
    headingWeight: 650,
    letterSpacing: "-0.014em",
    contentMeasure: "78rem",
  },
  components: {
    buttonPadding: 18,
    buttonShadow: "0 2px 5px rgb(17 24 39 / 0.18)",
    cardPadding: 22,
    cardHeaderHeight: 54,
    menuItemHeight: 38,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 28,
    titleMarginTop: "1.15em",
    titleMarginBottom: "0.5em",
    inputPaddingInline: 12,
    inputPaddingBlock: 5,
  },
  radius: { small: "0.375rem", medium: "0.625rem", large: "0.875rem" },
  shadow: "0 12px 32px rgb(15 23 42 / 0.12)",
  controlHeight: 32,
};
