/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "catppuccin-mocha",
  name: "Catppuccin Mocha",
  aliases: [],
  appearance: "dark",
  description: "A rich violet-charcoal dark adaptation with blue interactions.",
  source: {
    name: "Catppuccin Palette",
    url: "https://github.com/catppuccin/palette",
    revision: "v1.8.0",
    license: "MIT",
  },
  colors: {
    canvas: "#1e1e2e",
    surface: "#282839",
    surfaceRaised: "#313244",
    text: "#cdd6f4",
    textMuted: "#a6adc8",
    border: "#585b70",
    primary: "#89b4fa",
    primaryText: "#111827",
    focus: "#89b4fa",
    selection: "#45475a",
    selectionText: "#ffffff",
    codeBackground: "#181825",
  },
  typography: {
    sans: "Inter, ui-sans-serif, system-ui, sans-serif",
    mono: '"Fira Code", ui-monospace, monospace',
  },
  rhythm: {
    lineHeight: 1.55,
    headingWeight: 650,
    letterSpacing: "-0.014em",
    contentMeasure: "78rem",
  },
  components: {
    buttonPadding: 20,
    buttonShadow: "0 2px 5px rgb(17 24 39 / 0.18)",
    cardBorderWidth: 0,
    cardPadding: 24,
    cardHeaderHeight: 58,
    menuItemHeight: 40,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 30,
    titleMarginTop: "1.15em",
    titleMarginBottom: "0.5em",
    inputPaddingInline: 14,
    inputPaddingBlock: 6,
  },
  radius: { small: "0.5rem", medium: "0.75rem", large: "1rem" },
  shadow: "0 10px 30px rgb(10 10 20 / 0.42)",
  controlHeight: 36,
};
