/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "catppuccin-latte",
  name: "Catppuccin Latte",
  aliases: ["catppuccin"],
  appearance: "light",
  description: "A creamy light adaptation with lavender-blue interactions.",
  source: {
    name: "Catppuccin Palette",
    url: "https://github.com/catppuccin/palette",
    revision: "v1.8.0",
    license: "MIT",
  },
  colors: {
    canvas: "#eff1f5",
    surface: "#ffffff",
    surfaceRaised: "#ffffff",
    text: "#4c4f69",
    textMuted: "#6c6f85",
    border: "#bcc0cc",
    primary: "#1e66f5",
    primaryText: "#ffffff",
    link: "#1c60e8",
    focus: "#1e66f5",
    selection: "#c6d0f5",
    selectionText: "#303446",
    codeBackground: "#e6e9ef",
  },
  typography: {
    sans: "Inter, ui-sans-serif, system-ui, sans-serif",
    mono: '"Fira Code", ui-monospace, monospace',
  },
  rhythm: {
    lineHeight: 1.55,
    headingWeight: 650,
    letterSpacing: "-0.014em",
    contentMeasure: "78rem",
  },
  components: {
    buttonPadding: 20,
    buttonShadow: "0 2px 5px rgb(17 24 39 / 0.18)",
    cardBorderWidth: 0,
    cardPadding: 24,
    cardHeaderHeight: 58,
    menuItemHeight: 40,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 30,
    titleMarginTop: "1.15em",
    titleMarginBottom: "0.5em",
    inputPaddingInline: 14,
    inputPaddingBlock: 6,
  },
  radius: { small: "0.5rem", medium: "0.75rem", large: "1rem" },
  shadow: "0 10px 30px rgb(114 135 253 / 0.16)",
  controlHeight: 36,
};
