export default {
  id: "catppuccin-mocha",
  name: "Catppuccin Mocha",
  aliases: [],
  appearance: "dark",
  description: "A rich violet-charcoal dark adaptation with blue interactions.",
  source: {
    name: "Catppuccin Palette",
    url: "https://github.com/catppuccin/palette",
    revision: "v1.8.0",
    license: "MIT",
  },
  colors: {
    canvas: "#1e1e2e",
    surface: "#282839",
    surfaceRaised: "#313244",
    text: "#f5e0dc",
    textMuted: "#cdd6f4",
    border: "#585b70",
    primary: "#89b4fa",
    primaryText: "#111827",
    focus: "#89b4fa",
    selection: "#45475a",
    selectionText: "#ffffff",
    codeBackground: "#181825",
  },
  typography: {
    sans: "Inter, ui-sans-serif, system-ui, sans-serif",
    mono: "\"Fira Code\", ui-monospace, monospace",
  },
  rhythm: {
    lineHeight: 1.55,
    headingWeight: 650,
    letterSpacing: "-0.014em",
    contentMeasure: "78rem",
  },
  components: {
    buttonPadding: 18,
    buttonShadow: "0 2px 5px rgb(17 24 39 / 0.18)",
    cardPadding: 22,
    cardHeaderHeight: 54,
    menuItemHeight: 38,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 28,
    titleMarginTop: "1.15em",
    titleMarginBottom: "0.5em",
    inputPaddingInline: 12,
    inputPaddingBlock: 5,
  },
  radius: { small: "0.375rem", medium: "0.625rem", large: "0.875rem" },
  shadow: "0 12px 32px rgb(15 23 42 / 0.12)",
  controlHeight: 32,
};
