/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "catppuccin-frappe",
  name: "Catppuccin Frappé",
  aliases: [],
  appearance: "dark",
  description: "A muted blue-gray fixed dark adaptation.",
  prismTheme: "dracula",
  tableStyle: "striped",
  source: {
    name: "Catppuccin Palette",
    url: "https://github.com/catppuccin/palette",
    revision: "v1.8.0",
    license: "MIT",
  },
  colors: {
    canvas: "#303446",
    surface: "#383c4f",
    surfaceRaised: "#414559",
    text: "#c6d0f5",
    textMuted: "#a5adce",
    border: "#626880",
    primary: "#8caaee",
    primaryText: "#18202f",
    focus: "#8caaee",
    selection: "#51576d",
    selectionText: "#ffffff",
    codeBackground: "#292c3c",
  },
  typography: {
    sans: "Inter, ui-sans-serif, system-ui, sans-serif",
    mono: '"Fira Code", ui-monospace, monospace',
  },
  rhythm: {
    lineHeight: 1.55,
    headingWeight: 650,
    letterSpacing: "-0.014em",
    contentMeasure: "78rem",
  },
  components: {
    buttonPadding: 20,
    buttonShadow: "0 2px 5px rgb(17 24 39 / 0.18)",
    cardBorderWidth: 0,
    cardPadding: 24,
    cardHeaderHeight: 58,
    menuItemHeight: 40,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 30,
    titleMarginTop: "1.15em",
    titleMarginBottom: "0.5em",
    inputPaddingInline: 14,
    inputPaddingBlock: 6,
  },
  radius: { small: "0.5rem", medium: "0.75rem", large: "1rem" },
  shadow: "0 10px 30px rgb(20 24 40 / 0.32)",
  controlHeight: 36,
};
