export default {
  id: "catppuccin-frappe",
  name: "Catppuccin Frappé",
  aliases: [],
  appearance: "dark",
  description: "A muted blue-gray fixed dark adaptation.",
  source: {
    name: "Catppuccin Palette",
    url: "https://github.com/catppuccin/palette",
    revision: "v1.8.0",
    license: "MIT",
  },
  colors: {
    canvas: "#303446",
    surface: "#383c4f",
    surfaceRaised: "#414559",
    text: "#f2d5cf",
    textMuted: "#c6d0f5",
    border: "#626880",
    primary: "#8caaee",
    primaryText: "#18202f",
    focus: "#8caaee",
    selection: "#51576d",
    selectionText: "#ffffff",
    codeBackground: "#292c3c",
  },
  typography: {
    sans: "Inter, ui-sans-serif, system-ui, sans-serif",
    mono: "\"Fira Code\", ui-monospace, monospace",
  },
  rhythm: {
    lineHeight: 1.55,
    headingWeight: 650,
    letterSpacing: "-0.014em",
    contentMeasure: "78rem",
  },
  components: {
    buttonPadding: 18,
    buttonShadow: "0 2px 5px rgb(17 24 39 / 0.18)",
    cardPadding: 22,
    cardHeaderHeight: 54,
    menuItemHeight: 38,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 28,
    titleMarginTop: "1.15em",
    titleMarginBottom: "0.5em",
    inputPaddingInline: 12,
    inputPaddingBlock: 5,
  },
  radius: { small: "0.375rem", medium: "0.625rem", large: "0.875rem" },
  shadow: "0 12px 32px rgb(15 23 42 / 0.12)",
  controlHeight: 32,
};
