/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "default",
  name: "Default",
  aliases: [],
  appearance: "light",
  description: "A clear neutral canvas with confident blue interactions.",
  source: {
    name: "rtifact",
    url: "https://github.com/sirawats/rtifact",
    revision: "0.1.0",
    license: "MIT",
  },
  colors: {
    canvas: "#f8fafc",
    surface: "#ffffff",
    surfaceRaised: "#ffffff",
    text: "#0f172a",
    textMuted: "#475569",
    border: "#cbd5e1",
    primary: "#0958d9",
    primaryText: "#ffffff",
    focus: "#2563eb",
    selection: "#bfdbfe",
    selectionText: "#172554",
    codeBackground: "#e2e8f0",
  },
  typography: {
    sans: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    mono: '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
  },
  rhythm: {
    lineHeight: 1.55,
    headingWeight: 650,
    letterSpacing: "-0.012em",
    contentMeasure: "76rem",
  },
  components: {
    buttonPadding: 16,
    buttonShadow: "0 1px 2px rgb(15 23 42 / 0.14)",
    cardPadding: 24,
    cardHeaderHeight: 56,
    menuItemHeight: 40,
    menuItemMargin: 4,
    segmentedPadding: 2,
    tabGutter: 28,
    titleMarginTop: "1.2em",
    titleMarginBottom: "0.5em",
    inputPaddingInline: 11,
    inputPaddingBlock: 4,
  },
  radius: { small: "0.375rem", medium: "0.625rem", large: "0.875rem" },
  shadow: "0 12px 32px rgb(15 23 42 / 0.12)",
  controlHeight: 32,
};
