export default {
  id: "everforest-dark",
  name: "Everforest Dark",
  aliases: [],
  appearance: "dark",
  description: "A soft forest-dark canvas with moss-green interactions.",
  source: {
    name: "Everforest",
    url: "https://github.com/sainnhe/everforest",
    revision: "2.0.0",
    license: "MIT",
  },
  colors: {
    canvas: "#2d353b",
    surface: "#343f44",
    surfaceRaised: "#3d484d",
    text: "#f0ead3",
    textMuted: "#c5c0aa",
    border: "#5c6a72",
    primary: "#a7c080",
    primaryText: "#1e292e",
    focus: "#a7c080",
    selection: "#475258",
    selectionText: "#ffffff",
    codeBackground: "#252d32",
  },
  typography: {
    sans: '"Avenir Next", Avenir, ui-sans-serif, system-ui, sans-serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.6,
    headingWeight: 650,
    letterSpacing: "-0.01em",
    contentMeasure: "74rem",
  },
  components: {
    buttonPadding: 18,
    buttonShadow: "0 1px 3px rgb(60 56 54 / 0.16)",
    cardPadding: 22,
    cardHeaderHeight: 54,
    menuItemHeight: 38,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 28,
    titleMarginTop: "1.25em",
    titleMarginBottom: "0.55em",
    inputPaddingInline: 12,
    inputPaddingBlock: 5,
  },
  radius: { small: "0.375rem", medium: "0.625rem", large: "0.875rem" },
  shadow: "0 12px 32px rgb(15 23 42 / 0.12)",
  controlHeight: 32,
  status: {
    success: { foreground: "#d4ecc0", background: "#1e3a14", seed: "#a7c080" },
    warning: { foreground: "#fef3c7", background: "#3e2e04", seed: "#dbbc7f" },
    danger:  { foreground: "#fecaca", background: "#4e1414", seed: "#e67e80" },
    info:    { foreground: "#c8e8e4", background: "#0e2c2a", seed: "#7fbbb3" },
  },
};
