/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "everforest-light",
  name: "Everforest Light",
  aliases: ["everforest"],
  appearance: "light",
  description: "A gentle botanical light canvas with calm green interactions.",
  prismTheme: "duotone-light",
  tableStyle: "striped",
  source: {
    name: "Everforest",
    url: "https://github.com/sainnhe/everforest",
    revision: "2.0.0",
    license: "MIT",
  },
  colors: {
    canvas: "#fdf6e3",
    surface: "#fffbef",
    surfaceRaised: "#ffffff",
    text: "#3a4a44",
    textMuted: "#5c6a72",
    border: "#bdc9b8",
    primary: "#3a7460",
    primaryText: "#ffffff",
    focus: "#3a7460",
    selection: "#d5e2c8",
    selectionText: "#25352f",
    codeBackground: "#efebd4",
  },
  typography: {
    sans: '"Avenir Next", Avenir, ui-sans-serif, system-ui, sans-serif',
    heading: 'ui-serif, Georgia, Cambria, "Times New Roman", serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.62,
    headingWeight: 600,
    letterSpacing: "-0.006em",
    contentMeasure: "74rem",
  },
  components: {
    buttonPadding: 20,
    buttonShadow: "0 1px 3px rgb(60 56 54 / 0.16)",
    cardBorderWidth: 0,
    cardPadding: 24,
    cardHeaderHeight: 58,
    menuItemHeight: 40,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 28,
    titleMarginTop: "1.3em",
    titleMarginBottom: "0.6em",
    inputPaddingInline: 14,
    inputPaddingBlock: 6,
  },
  radius: { small: "0.375rem", medium: "0.625rem", large: "0.875rem" },
  shadow: "0 10px 28px rgb(58 116 96 / 0.12)",
  controlHeight: 36,
  status: {
    success: {
      foreground: "#274828",
      background: "#e1f0d7",
      border: "#8da101",
      seed: "#8da101",
    },
    warning: {
      foreground: "#604400",
      background: "#f5e6b3",
      border: "#dfa000",
      seed: "#dfa000",
    },
    danger: {
      foreground: "#701815",
      background: "#f8dcd8",
      border: "#f85552",
      seed: "#f85552",
    },
    info: {
      foreground: "#0e4454",
      background: "#d2ebf5",
      border: "#3a94c5",
      seed: "#3a94c5",
    },
  },
};
