export default {
  id: "everforest-light",
  name: "Everforest Light",
  aliases: ["everforest"],
  appearance: "light",
  description: "A gentle botanical light canvas with calm green interactions.",
  source: {
    name: "Everforest",
    url: "https://github.com/sainnhe/everforest",
    revision: "2.0.0",
    license: "MIT",
  },
  colors: {
    canvas: "#fdf6e3",
    surface: "#fffbef",
    surfaceRaised: "#ffffff",
    text: "#3a4a44",
    textMuted: "#5c6a72",
    border: "#bdc9b8",
    primary: "#3a7460",
    primaryText: "#ffffff",
    focus: "#3a7460",
    selection: "#d5e2c8",
    selectionText: "#25352f",
    codeBackground: "#efebd4",
  },
  typography: {
    sans: '"Avenir Next", Avenir, ui-sans-serif, system-ui, sans-serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.6,
    headingWeight: 650,
    letterSpacing: "-0.01em",
    contentMeasure: "74rem",
  },
  components: {
    buttonPadding: 18,
    buttonShadow: "0 1px 3px rgb(60 56 54 / 0.16)",
    cardPadding: 22,
    cardHeaderHeight: 54,
    menuItemHeight: 38,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 28,
    titleMarginTop: "1.25em",
    titleMarginBottom: "0.55em",
    inputPaddingInline: 12,
    inputPaddingBlock: 5,
  },
  radius: { small: "0.375rem", medium: "0.625rem", large: "0.875rem" },
  shadow: "0 12px 32px rgb(15 23 42 / 0.12)",
  controlHeight: 32,
  status: {
    success: { foreground: "#2e3800", background: "#e0ecc0", seed: "#8da101" },
    warning: { foreground: "#4c3800", background: "#f8f0c0", seed: "#dfa000" },
    danger:  { foreground: "#5c0800", background: "#fce0de", seed: "#f85552" },
    info:    { foreground: "#0e3654", background: "#cce4f4", seed: "#3a94c5" },
  },
};
