/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "everforest-dark",
  name: "Everforest Dark",
  aliases: [],
  appearance: "dark",
  description: "A soft forest-dark canvas with moss-green interactions.",
  prismTheme: "duotone-forest",
  tableStyle: "striped",
  source: {
    name: "Everforest",
    url: "https://github.com/sainnhe/everforest",
    revision: "2.0.0",
    license: "MIT",
  },
  colors: {
    canvas: "#2d353b",
    surface: "#343f44",
    surfaceRaised: "#3d484d",
    text: "#f0ead3",
    textMuted: "#c5c0aa",
    border: "#5c6a72",
    primary: "#a7c080",
    primaryText: "#1e292e",
    focus: "#a7c080",
    selection: "#475258",
    selectionText: "#ffffff",
    codeBackground: "#252d32",
  },
  typography: {
    sans: '"Avenir Next", Avenir, ui-sans-serif, system-ui, sans-serif',
    heading: 'ui-serif, Georgia, Cambria, "Times New Roman", serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.62,
    headingWeight: 600,
    letterSpacing: "-0.006em",
    contentMeasure: "74rem",
  },
  components: {
    buttonPadding: 20,
    buttonShadow: "0 1px 3px rgb(60 56 54 / 0.16)",
    cardBorderWidth: 0,
    cardPadding: 24,
    cardHeaderHeight: 58,
    menuItemHeight: 40,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 28,
    titleMarginTop: "1.3em",
    titleMarginBottom: "0.6em",
    inputPaddingInline: 14,
    inputPaddingBlock: 6,
  },
  radius: { small: "0.375rem", medium: "0.625rem", large: "0.875rem" },
  shadow: "0 10px 28px rgb(0 0 0 / 0.28)",
  controlHeight: 36,
  status: {
    success: {
      foreground: "#d4ecc0",
      background: "#1e3a14",
      border: "#a7c080",
      seed: "#a7c080",
    },
    warning: {
      foreground: "#fef3c7",
      background: "#3e2e04",
      border: "#dbbc7f",
      seed: "#dbbc7f",
    },
    danger: {
      foreground: "#fecaca",
      background: "#4e1414",
      border: "#e67e80",
      seed: "#e67e80",
    },
    info: {
      foreground: "#c8e8e4",
      background: "#0e2c2a",
      border: "#7fbbb3",
      seed: "#7fbbb3",
    },
  },
};
