export default {
  id: "github-dark-dimmed",
  name: "GitHub Dark Dimmed",
  aliases: [],
  appearance: "dark",
  description: "A softened charcoal forge-inspired fixed dark variant.",
  source: {
    name: "Primer Primitives",
    url: "https://github.com/primer/primitives",
    revision: "v11.9.0",
    license: "MIT",
  },
  colors: {
    canvas: "#22272e",
    surface: "#2d333b",
    surfaceRaised: "#373e47",
    text: "#f0f3f6",
    textMuted: "#adbac7",
    border: "#444c56",
    primary: "#238636",
    primaryAccent: "#3fb950",
    primaryAccentHover: "#56d364",
    primaryText: "#ffffff",
    link: "#6cb6ff",
    focus: "#6cb6ff",
    selection: "#316dca",
    selectionText: "#ffffff",
    codeBackground: "#373e47",
  },
  typography: {
    sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.5,
    headingWeight: 600,
    letterSpacing: "-0.012em",
    contentMeasure: "80rem",
  },
  components: {
    buttonPadding: 14,
    buttonShadow: "0 1px 0 rgb(28 33 40 / 0.12)",
    cardPadding: 20,
    cardHeaderHeight: 54,
    menuItemHeight: 36,
    menuItemMargin: 2,
    segmentedPadding: 2,
    tabGutter: 24,
    titleMarginTop: "1.25em",
    titleMarginBottom: "0.5em",
    inputPaddingInline: 12,
    inputPaddingBlock: 4,
  },
  radius: { small: "0.25rem", medium: "0.375rem", large: "0.5rem" },
  shadow: "0 3px 8px rgb(28 33 40 / 0.28)",
  controlHeight: 32,
  status: {
    success: {
      foreground: "#56d364",
      background: "#1c3326",
      border: "#238636",
      seed: "#238636",
    },
    warning: {
      foreground: "#c69026",
      background: "#2b261b",
      border: "#9e6a03",
      seed: "#9e6a03",
    },
    danger: {
      foreground: "#f47067",
      background: "#342226",
      border: "#da3633",
      seed: "#da3633",
    },
    info: {
      foreground: "#6cb6ff",
      background: "#1e2f45",
      border: "#6cb6ff",
      seed: "#6cb6ff",
    },
  },
};
