export default {
  id: "github-dark",
  name: "GitHub Dark",
  aliases: [],
  appearance: "dark",
  description: "A high-contrast forge-inspired dark interface.",
  source: {
    name: "Primer Primitives",
    url: "https://github.com/primer/primitives",
    revision: "v11.9.0",
    license: "MIT",
  },
  colors: {
    canvas: "#0d1117",
    surface: "#161b22",
    surfaceRaised: "#21262d",
    text: "#f0f6fc",
    textMuted: "#9da7b1",
    border: "#30363d",
    primary: "#238636",
    primaryText: "#ffffff",
    link: "#58a6ff",
    focus: "#58a6ff",
    selection: "#1f6feb",
    selectionText: "#ffffff",
    codeBackground: "#21262d",
  },
  typography: {
    sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.5,
    headingWeight: 600,
    letterSpacing: "-0.012em",
    contentMeasure: "80rem",
  },
  components: {
    buttonPadding: 14,
    buttonShadow: "0 1px 0 rgb(1 4 9 / 0.12)",
    cardPadding: 20,
    cardHeaderHeight: 54,
    menuItemHeight: 36,
    menuItemMargin: 2,
    segmentedPadding: 2,
    tabGutter: 24,
    titleMarginTop: "1.25em",
    titleMarginBottom: "0.5em",
    inputPaddingInline: 12,
    inputPaddingBlock: 4,
  },
  radius: { small: "0.25rem", medium: "0.375rem", large: "0.5rem" },
  shadow: "0 3px 8px rgb(1 4 9 / 0.32)",
  controlHeight: 32,
  status: {
    success: {
      foreground: "#3fb950",
      background: "#122e17",
      border: "#238636",
      seed: "#238636",
    },
    warning: {
      foreground: "#d29922",
      background: "#272115",
      border: "#9e6a03",
      seed: "#9e6a03",
    },
    danger: {
      foreground: "#f85149",
      background: "#30191e",
      border: "#da3633",
      seed: "#da3633",
    },
    info: {
      foreground: "#58a6ff",
      background: "#112338",
      border: "#58a6ff",
      seed: "#58a6ff",
    },
  },
};
