export default {
  id: "github-dark",
  name: "GitHub Dark",
  aliases: [],
  appearance: "dark",
  description: "A high-contrast forge-inspired dark interface.",
  source: {
    name: "Primer Primitives",
    url: "https://github.com/primer/primitives",
    revision: "v11.9.0",
    license: "MIT",
  },
  colors: {
    canvas: "#0d1117",
    surface: "#161b22",
    surfaceRaised: "#21262d",
    text: "#f0f6fc",
    textMuted: "#9da7b1",
    border: "#3d444d",
    primary: "#58a6ff",
    primaryText: "#07101f",
    focus: "#58a6ff",
    selection: "#264f78",
    selectionText: "#ffffff",
    codeBackground: "#21262d",
  },
  typography: {
    sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.5,
    headingWeight: 600,
    letterSpacing: "-0.012em",
    contentMeasure: "80rem",
  },
  components: {
    buttonPadding: 12,
    buttonShadow: "0 1px 0 rgb(31 35 40 / 0.12)",
    cardPadding: 16,
    cardHeaderHeight: 44,
    menuItemHeight: 32,
    menuItemMargin: 2,
    segmentedPadding: 2,
    tabGutter: 24,
    titleMarginTop: "1em",
    titleMarginBottom: "0.4em",
    inputPaddingInline: 10,
    inputPaddingBlock: 3,
  },
  radius: { small: "0.25rem", medium: "0.375rem", large: "0.625rem" },
  shadow: "0 12px 32px rgb(15 23 42 / 0.12)",
  controlHeight: 30,
};
