export default {
  id: "github-light",
  name: "GitHub Light",
  aliases: ["github"],
  appearance: "light",
  description: "A crisp forge-inspired light interface with compact surfaces.",
  source: {
    name: "Primer Primitives",
    url: "https://github.com/primer/primitives",
    revision: "v11.9.0",
    license: "MIT",
  },
  colors: {
    canvas: "#f6f8fa",
    surface: "#ffffff",
    surfaceRaised: "#ffffff",
    text: "#1f2328",
    textMuted: "#59636e",
    border: "#d0d7de",
    primary: "#0969da",
    primaryText: "#ffffff",
    focus: "#0969da",
    selection: "#b6d7fe",
    selectionText: "#111827",
    codeBackground: "#eff2f5",
  },
  typography: {
    sans: "-apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
    mono: "ui-monospace, \"SFMono-Regular\", Consolas, monospace",
  },
  rhythm: {
    lineHeight: 1.5,
    headingWeight: 600,
    letterSpacing: "-0.012em",
    contentMeasure: "80rem",
  },
  components: {
    buttonPadding: 12,
    buttonShadow: "0 1px 0 rgb(31 35 40 / 0.12)",
    cardPadding: 16,
    cardHeaderHeight: 44,
    menuItemHeight: 32,
    menuItemMargin: 2,
    segmentedPadding: 2,
    tabGutter: 24,
    titleMarginTop: "1em",
    titleMarginBottom: "0.4em",
    inputPaddingInline: 10,
    inputPaddingBlock: 3,
  },
  radius: { small: "0.25rem", medium: "0.375rem", large: "0.625rem" },
  shadow: "0 12px 32px rgb(15 23 42 / 0.12)",
  controlHeight: 30,
};
