/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "github-light",
  name: "GitHub Light",
  aliases: ["github"],
  appearance: "light",
  description: "A crisp forge-inspired light interface with compact surfaces.",
  source: {
    name: "Primer Primitives",
    url: "https://github.com/primer/primitives",
    revision: "v11.9.0",
    license: "MIT",
  },
  colors: {
    canvas: "#f6f8fa",
    surface: "#ffffff",
    surfaceRaised: "#ffffff",
    text: "#1f2328",
    textMuted: "#59636e",
    border: "#d0d7de",
    primary: "#1f883d",
    primaryText: "#ffffff",
    link: "#0969da",
    focus: "#0969da",
    selection: "#b6d7fe",
    selectionText: "#091e42",
    codeBackground: "#eff2f5",
  },
  typography: {
    sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.5,
    headingWeight: 600,
    letterSpacing: "-0.012em",
    contentMeasure: "80rem",
  },
  components: {
    buttonPadding: 14,
    buttonShadow: "0 1px 0 rgb(31 35 40 / 0.12)",
    cardPadding: 20,
    cardHeaderHeight: 54,
    menuItemHeight: 36,
    menuItemMargin: 2,
    segmentedPadding: 2,
    tabGutter: 24,
    titleMarginTop: "1.25em",
    titleMarginBottom: "0.5em",
    inputPaddingInline: 12,
    inputPaddingBlock: 4,
  },
  radius: { small: "0.25rem", medium: "0.375rem", large: "0.5rem" },
  shadow: "0 3px 8px rgb(31 35 40 / 0.12)",
  controlHeight: 32,
  status: {
    success: {
      foreground: "#1a7f37",
      background: "#dafbe1",
      border: "#1f883d",
      seed: "#1f883d",
    },
    warning: {
      foreground: "#7d4e00",
      background: "#fff8c5",
      border: "#9a6700",
      seed: "#9a6700",
    },
    danger: {
      foreground: "#a40e26",
      background: "#ffebe9",
      border: "#cf222e",
      seed: "#cf222e",
    },
    info: {
      foreground: "#0969da",
      background: "#ddf4ff",
      border: "#0969da",
      seed: "#0969da",
    },
  },
};
