/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "gruvbox-dark",
  name: "Gruvbox Dark",
  aliases: [],
  appearance: "dark",
  description: "A warm charcoal adaptation with amber-orange interactions.",
  source: {
    name: "Gruvbox",
    url: "https://github.com/morhetz/gruvbox",
    revision: "v2.0.0",
    license: "MIT",
  },
  colors: {
    canvas: "#282828",
    surface: "#32302f",
    surfaceRaised: "#3c3836",
    text: "#fbf1c7",
    textMuted: "#d5c4a1",
    border: "#665c54",
    primary: "#fabd2f",
    primaryText: "#282828",
    focus: "#fabd2f",
    selection: "#504945",
    selectionText: "#ffffff",
    codeBackground: "#1d2021",
  },
  typography: {
    sans: '"Avenir Next", Avenir, ui-sans-serif, system-ui, sans-serif',
    heading: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.52,
    headingWeight: 700,
    letterSpacing: "-0.01em",
    contentMeasure: "72rem",
  },
  components: {
    buttonPadding: 14,
    buttonShadow: "0 1px 3px rgb(60 56 54 / 0.16)",
    cardPadding: 18,
    cardHeaderHeight: 48,
    menuItemHeight: 34,
    menuItemMargin: 3,
    segmentedPadding: 2,
    tabGutter: 24,
    titleMarginTop: "1.1em",
    titleMarginBottom: "0.45em",
    inputPaddingInline: 10,
    inputPaddingBlock: 4,
  },
  radius: { small: "0.125rem", medium: "0.25rem", large: "0.375rem" },
  shadow: "none",
  controlHeight: 32,
  status: {
    success: { foreground: "#e0e3a0", background: "#353a08", seed: "#b8bb26" },
    warning: { foreground: "#fef3c7", background: "#4a3a00", seed: "#fabd2f" },
    danger: { foreground: "#fecaca", background: "#5c1212", seed: "#fb4934" },
    info: { foreground: "#c8e0de", background: "#1a3432", seed: "#83a598" },
  },
};
