/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "gruvbox-light",
  name: "Gruvbox Light",
  aliases: ["gruvbox"],
  appearance: "light",
  description: "A warm parchment adaptation with earthy red interactions.",
  prismTheme: "gruvbox-light",
  tableStyle: "striped",
  source: {
    name: "Gruvbox",
    url: "https://github.com/morhetz/gruvbox",
    revision: "v2.0.0",
    license: "MIT",
  },
  colors: {
    canvas: "#fbf1c7",
    surface: "#fff8d8",
    surfaceRaised: "#ffffff",
    text: "#3c3836",
    textMuted: "#665c54",
    border: "#bdae93",
    primary: "#9d0006",
    primaryText: "#ffffff",
    focus: "#9d0006",
    selection: "#d5c4a1",
    selectionText: "#282828",
    codeBackground: "#ebdbb2",
  },
  typography: {
    sans: '"Avenir Next", Avenir, ui-sans-serif, system-ui, sans-serif',
    heading: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.52,
    headingWeight: 700,
    letterSpacing: "-0.01em",
    contentMeasure: "72rem",
  },
  components: {
    buttonPadding: 14,
    buttonShadow: "0 1px 3px rgb(60 56 54 / 0.16)",
    cardPadding: 18,
    cardHeaderHeight: 48,
    menuItemHeight: 34,
    menuItemMargin: 3,
    segmentedPadding: 2,
    tabGutter: 24,
    titleMarginTop: "1.1em",
    titleMarginBottom: "0.45em",
    inputPaddingInline: 10,
    inputPaddingBlock: 4,
  },
  radius: { small: "0.125rem", medium: "0.25rem", large: "0.375rem" },
  shadow: "none",
  controlHeight: 32,
  status: {
    success: { foreground: "#2b4010", background: "#e1eab5", seed: "#98971a" },
    warning: { foreground: "#583800", background: "#f3d898", seed: "#d79921" },
    danger: { foreground: "#700808", background: "#f8d8d4", seed: "#cc241d" },
    info: { foreground: "#0e4042", background: "#cbe8eb", seed: "#458588" },
  },
};
