export default {
  id: "gruvbox-dark",
  name: "Gruvbox Dark",
  aliases: [],
  appearance: "dark",
  description: "A warm charcoal adaptation with amber-orange interactions.",
  source: {
    name: "Gruvbox",
    url: "https://github.com/morhetz/gruvbox",
    revision: "v2.0.0",
    license: "MIT",
  },
  colors: {
    canvas: "#282828",
    surface: "#32302f",
    surfaceRaised: "#3c3836",
    text: "#fbf1c7",
    textMuted: "#d5c4a1",
    border: "#665c54",
    primary: "#fabd2f",
    primaryText: "#282828",
    focus: "#fabd2f",
    selection: "#504945",
    selectionText: "#ffffff",
    codeBackground: "#1d2021",
  },
  typography: {
    sans: '"Avenir Next", Avenir, ui-sans-serif, system-ui, sans-serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.6,
    headingWeight: 650,
    letterSpacing: "-0.01em",
    contentMeasure: "74rem",
  },
  components: {
    buttonPadding: 18,
    buttonShadow: "0 1px 3px rgb(60 56 54 / 0.16)",
    cardPadding: 22,
    cardHeaderHeight: 54,
    menuItemHeight: 38,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 28,
    titleMarginTop: "1.25em",
    titleMarginBottom: "0.55em",
    inputPaddingInline: 12,
    inputPaddingBlock: 5,
  },
  radius: { small: "0.375rem", medium: "0.625rem", large: "0.875rem" },
  shadow: "0 12px 32px rgb(15 23 42 / 0.12)",
  controlHeight: 32,
};
