export default {
  id: "gruvbox-light",
  name: "Gruvbox Light",
  aliases: ["gruvbox"],
  appearance: "light",
  description: "A warm parchment adaptation with earthy red interactions.",
  source: {
    name: "Gruvbox",
    url: "https://github.com/morhetz/gruvbox",
    revision: "v2.0.0",
    license: "MIT",
  },
  colors: {
    canvas: "#fbf1c7",
    surface: "#fff8d8",
    surfaceRaised: "#ffffff",
    text: "#3c3836",
    textMuted: "#665c54",
    border: "#bdae93",
    primary: "#9d0006",
    primaryText: "#ffffff",
    focus: "#9d0006",
    selection: "#d5c4a1",
    selectionText: "#282828",
    codeBackground: "#ebdbb2",
  },
  typography: {
    sans: '"Avenir Next", Avenir, ui-sans-serif, system-ui, sans-serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.6,
    headingWeight: 650,
    letterSpacing: "-0.01em",
    contentMeasure: "74rem",
  },
  components: {
    buttonPadding: 18,
    buttonShadow: "0 1px 3px rgb(60 56 54 / 0.16)",
    cardPadding: 22,
    cardHeaderHeight: 54,
    menuItemHeight: 38,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 28,
    titleMarginTop: "1.25em",
    titleMarginBottom: "0.55em",
    inputPaddingInline: 12,
    inputPaddingBlock: 5,
  },
  radius: { small: "0.375rem", medium: "0.625rem", large: "0.875rem" },
  shadow: "0 12px 32px rgb(15 23 42 / 0.12)",
  controlHeight: 32,
  status: {
    success: { foreground: "#282828", background: "#eef0c5", seed: "#98971a" },
    warning: { foreground: "#3c3836", background: "#fdf6d0", seed: "#d79921" },
    danger:  { foreground: "#4e0404", background: "#f8e0de", seed: "#cc241d" },
    info:    { foreground: "#1b4040", background: "#d8ecec", seed: "#458588" },
  },
};
