export default {
  id: "material-dark",
  name: "Material Dark",
  aliases: [],
  appearance: "dark",
  description: "A tonal dark surface system with luminous violet accents.",
  source: {
    name: "Material Web",
    url: "https://github.com/material-components/material-web",
    revision: "v2.4.1",
    license: "Apache-2.0",
  },
  colors: {
    canvas: "#1c1b1f",
    surface: "#242126",
    surfaceRaised: "#2f2b32",
    text: "#e6e1e5",
    textMuted: "#cac4d0",
    border: "#938f99",
    primary: "#d0bcff",
    primaryText: "#27134f",
    focus: "#d0bcff",
    selection: "#4f378b",
    selectionText: "#f5efff",
    codeBackground: "#2f2b32",
  },
  typography: {
    sans: "Roboto, \"Noto Sans\", ui-sans-serif, system-ui, sans-serif",
    mono: "\"Roboto Mono\", ui-monospace, monospace",
  },
  rhythm: {
    lineHeight: 1.55,
    headingWeight: 500,
    letterSpacing: "-0.006em",
    contentMeasure: "76rem",
  },
  components: {
    buttonPadding: 24,
    buttonShadow: "0 2px 4px rgb(29 27 32 / 0.2)",
    cardPadding: 24,
    cardHeaderHeight: 64,
    menuItemHeight: 44,
    menuItemMargin: 6,
    segmentedPadding: 4,
    tabGutter: 32,
    titleMarginTop: "1.3em",
    titleMarginBottom: "0.6em",
    inputPaddingInline: 16,
    inputPaddingBlock: 8,
  },
  radius: { small: "0.5rem", medium: "0.75rem", large: "1.25rem" },
  shadow: "0 3px 12px rgb(0 0 0 / 0.42)",
  controlHeight: 40,
};
