/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "material-light",
  name: "Material Light",
  aliases: ["material"],
  appearance: "light",
  description:
    "A tonal light surface system with rounded, deliberate controls.",
  source: {
    name: "Material Web",
    url: "https://github.com/material-components/material-web",
    revision: "v2.4.1",
    license: "Apache-2.0",
  },
  colors: {
    canvas: "#fffbfe",
    surface: "#f3edf7",
    surfaceRaised: "#f3edf7",
    text: "#1d1b20",
    textMuted: "#49454f",
    border: "#79747e",
    primary: "#6750a4",
    primaryText: "#ffffff",
    focus: "#6750a4",
    selection: "#eaddff",
    selectionText: "#21005d",
    codeBackground: "#f3edf7",
  },
  typography: {
    sans: 'Roboto, "Noto Sans", ui-sans-serif, system-ui, sans-serif',
    mono: '"Roboto Mono", ui-monospace, monospace',
  },
  rhythm: {
    lineHeight: 1.55,
    headingWeight: 500,
    letterSpacing: "-0.006em",
    contentMeasure: "76rem",
  },
  components: {
    buttonPadding: 24,
    buttonShadow: "0 2px 4px rgb(29 27 32 / 0.2)",
    cardBorderWidth: 0,
    cardPadding: 24,
    cardHeaderHeight: 64,
    menuItemHeight: 44,
    menuItemMargin: 6,
    segmentedPadding: 4,
    tabGutter: 32,
    titleMarginTop: "1.3em",
    titleMarginBottom: "0.6em",
    inputPaddingInline: 16,
    inputPaddingBlock: 8,
  },
  radius: { small: "0.5rem", medium: "0.75rem", large: "1.25rem" },
  shadow: "0 3px 10px rgb(29 27 32 / 0.16)",
  controlHeight: 40,
};
