export default {
  id: "obsidian-baseline-dark",
  name: "Obsidian Baseline Dark",
  aliases: [],
  appearance: "dark",
  description:
    "An original typographic dark canvas inspired by Baseline's hierarchy.",
  source: {
    name: "Baseline for Obsidian",
    url: "https://github.com/aaaaalexis/obsidian-baseline",
    revision: "3.2.11",
    license: "MIT",
  },
  colors: {
    canvas: "#202224",
    surface: "#292c2f",
    surfaceRaised: "#32363a",
    text: "#f1efeb",
    textMuted: "#c3beb6",
    border: "#50565b",
    primary: "#8fc4df",
    primaryText: "#102936",
    focus: "#8fc4df",
    selection: "#3d5c6c",
    selectionText: "#ffffff",
    codeBackground: "#191b1d",
  },
  typography: {
    sans: '"Source Sans 3", "Segoe UI", ui-sans-serif, system-ui, sans-serif',
    heading: 'ui-serif, Georgia, Cambria, "Times New Roman", serif',
    mono: '"Source Code Pro", ui-monospace, monospace',
  },
  rhythm: {
    lineHeight: 1.62,
    headingWeight: 700,
    letterSpacing: "-0.012em",
    contentMeasure: "72rem",
  },
  components: {
    buttonPadding: 18,
    buttonShadow: "none",
    cardPadding: 24,
    cardHeaderHeight: 56,
    menuItemHeight: 40,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 30,
    titleMarginTop: "1.3em",
    titleMarginBottom: "0.55em",
    inputPaddingInline: 12,
    inputPaddingBlock: 5,
  },
  radius: { small: "0.25rem", medium: "0.5rem", large: "0.75rem" },
  shadow: "none",
  controlHeight: 36,
  status: {
    success: { border: "#50565b" },
    warning: { border: "#50565b" },
    danger: { border: "#50565b" },
    info: { border: "#50565b" },
  },
};
