/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "obsidian-minimal-light",
  name: "Obsidian Minimal Light",
  aliases: ["obsidian-minimal"],
  appearance: "light",
  description:
    "An original restrained reading canvas inspired by Minimal's rhythm.",
  source: {
    name: "Minimal for Obsidian",
    url: "https://github.com/kepano/obsidian-minimal",
    revision: "8.2.0",
    license: "MIT",
  },
  colors: {
    canvas: "#f7f7f5",
    surface: "#ffffff",
    surfaceRaised: "#ffffff",
    text: "#202020",
    textMuted: "#5f5f5b",
    border: "#d5d5d0",
    primary: "#4b50a8",
    primaryText: "#ffffff",
    focus: "#4b50a8",
    selection: "#d9daf5",
    selectionText: "#202044",
    codeBackground: "#ecece8",
  },
  typography: {
    sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.68,
    headingWeight: 600,
    letterSpacing: "-0.018em",
    contentMeasure: "68rem",
  },
  components: {
    buttonPadding: 14,
    buttonShadow: "none",
    cardBorderWidth: 0,
    cardPadding: 18,
    cardHeaderHeight: 48,
    menuItemHeight: 34,
    menuItemMargin: 2,
    segmentedPadding: 2,
    tabGutter: 22,
    titleMarginTop: "1.4em",
    titleMarginBottom: "0.55em",
    inputPaddingInline: 10,
    inputPaddingBlock: 4,
  },
  radius: { small: "0.25rem", medium: "0.375rem", large: "0.5rem" },
  shadow: "none",
  controlHeight: 32,
};
