/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "one-dark",
  name: "One Dark",
  aliases: ["onedark"],
  appearance: "dark",
  description: "A focused editor-dark adaptation with cool blue interactions.",
  source: {
    name: "Atom One Dark syntax",
    url: "https://github.com/atom/one-dark-syntax",
    revision: "v1.3.0",
    license: "MIT",
  },
  colors: {
    canvas: "#21252b",
    surface: "#282c34",
    surfaceRaised: "#303640",
    text: "#e5e9f0",
    textMuted: "#abb2bf",
    border: "#4b5263",
    primary: "#61afef",
    primaryText: "#15202b",
    focus: "#61afef",
    selection: "#3e4451",
    selectionText: "#ffffff",
    codeBackground: "#1f2329",
  },
  typography: {
    sans: "Inter, ui-sans-serif, system-ui, sans-serif",
    mono: '"JetBrains Mono", "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.48,
    headingWeight: 600,
    letterSpacing: "-0.015em",
    contentMeasure: "78rem",
  },
  components: {
    buttonPadding: 14,
    buttonShadow: "none",
    cardBorderWidth: 0,
    cardPadding: 18,
    cardHeaderHeight: 46,
    menuItemHeight: 34,
    menuItemMargin: 3,
    segmentedPadding: 2,
    tabGutter: 24,
    titleMarginTop: "1em",
    titleMarginBottom: "0.4em",
    inputPaddingInline: 10,
    inputPaddingBlock: 4,
  },
  radius: { small: "0.25rem", medium: "0.375rem", large: "0.5rem" },
  shadow: "none",
  controlHeight: 32,
  status: {
    success: { foreground: "#d4ecc0", background: "#1e3810", seed: "#98c379" },
    warning: { foreground: "#fef3c7", background: "#4a3800", seed: "#e5c07b" },
    danger: { foreground: "#fecaca", background: "#4e1010", seed: "#e06c75" },
    info: { foreground: "#dbeafe", background: "#1a3a5c", seed: "#61afef" },
  },
};
