export default {
  id: "solarized-dark",
  name: "Solarized Dark",
  aliases: [],
  appearance: "dark",
  description: "A deep teal low-glare dark canvas with cyan interactions.",
  source: {
    name: "Solarized",
    url: "https://github.com/altercation/solarized",
    revision: "v1.0.0-beta.2",
    license: "MIT",
  },
  colors: {
    canvas: "#002b36",
    surface: "#073642",
    surfaceRaised: "#0c4552",
    text: "#fdf6e3",
    textMuted: "#b8c4bd",
    border: "#43646b",
    primary: "#5ccfc5",
    primaryText: "#002b36",
    focus: "#5ccfc5",
    selection: "#1f5864",
    selectionText: "#ffffff",
    codeBackground: "#073642",
  },
  typography: {
    sans: '"Avenir Next", Avenir, ui-sans-serif, system-ui, sans-serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.6,
    headingWeight: 650,
    letterSpacing: "-0.01em",
    contentMeasure: "74rem",
  },
  components: {
    buttonPadding: 18,
    buttonShadow: "0 1px 3px rgb(60 56 54 / 0.16)",
    cardPadding: 22,
    cardHeaderHeight: 54,
    menuItemHeight: 38,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 28,
    titleMarginTop: "1.25em",
    titleMarginBottom: "0.55em",
    inputPaddingInline: 12,
    inputPaddingBlock: 5,
  },
  radius: { small: "0.375rem", medium: "0.625rem", large: "0.875rem" },
  shadow: "0 12px 32px rgb(15 23 42 / 0.12)",
  controlHeight: 32,
};
