/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "solarized-dark",
  name: "Solarized Dark",
  aliases: [],
  appearance: "dark",
  description: "A deep teal low-glare dark canvas with cyan interactions.",
  prismTheme: "solarized-dark-atom",
  tableStyle: "rows",
  source: {
    name: "Solarized",
    url: "https://github.com/altercation/solarized",
    revision: "v1.0.0-beta.2",
    license: "MIT",
  },
  colors: {
    canvas: "#002b36",
    surface: "#073642",
    surfaceRaised: "#0c4552",
    text: "#fdf6e3",
    textMuted: "#b8c4bd",
    border: "#43646b",
    primary: "#2aa198",
    primaryAccent: "#2aa198",
    primaryAccentHover: "#30ada4",
    primaryText: "#002b36",
    focus: "#2aa198",
    selection: "#1f5864",
    selectionText: "#ffffff",
    codeBackground: "#073642",
  },
  typography: {
    sans: '"Avenir Next", Avenir, ui-sans-serif, system-ui, sans-serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.6,
    headingWeight: 600,
    letterSpacing: "-0.01em",
    contentMeasure: "74rem",
  },
  components: {
    buttonPadding: 18,
    buttonShadow: "0 1px 3px rgb(60 56 54 / 0.16)",
    cardPadding: 22,
    cardHeaderHeight: 54,
    menuItemHeight: 38,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 28,
    titleMarginTop: "1.25em",
    titleMarginBottom: "0.55em",
    inputPaddingInline: 12,
    inputPaddingBlock: 5,
  },
  radius: { small: "0.25rem", medium: "0.375rem", large: "0.5rem" },
  shadow: "0 1px 2px rgb(0 0 0 / 0.32)",
  controlHeight: 34,
  status: {
    success: { foreground: "#c4d870", background: "#2a3a00", seed: "#859900" },
    warning: { foreground: "#fef3c7", background: "#3c2c00", seed: "#b58900" },
    danger: { foreground: "#fecaca", background: "#3c1010", seed: "#dc322f" },
    info: { foreground: "#dbeafe", background: "#0a2040", seed: "#268bd2" },
  },
};
