/** @satisfies {import("../themes.js").ThemeDefinition} */
export default {
  id: "solarized-light",
  name: "Solarized Light",
  aliases: ["solarized"],
  appearance: "light",
  description: "A warm low-glare light canvas with cyan-blue structure.",
  prismTheme: "solarizedlight",
  tableStyle: "rows",
  source: {
    name: "Solarized",
    url: "https://github.com/altercation/solarized",
    revision: "v1.0.0-beta.2",
    license: "MIT",
  },
  colors: {
    canvas: "#fdf6e3",
    surface: "#fffdf5",
    surfaceRaised: "#ffffff",
    text: "#073642",
    textMuted: "#586e75",
    border: "#c8c2ad",
    primary: "#006d83",
    primaryText: "#ffffff",
    focus: "#006d83",
    selection: "#d7e6bd",
    selectionText: "#073642",
    codeBackground: "#eee8d5",
  },
  typography: {
    sans: '"Avenir Next", Avenir, ui-sans-serif, system-ui, sans-serif',
    mono: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
  },
  rhythm: {
    lineHeight: 1.6,
    headingWeight: 600,
    letterSpacing: "-0.01em",
    contentMeasure: "74rem",
  },
  components: {
    buttonPadding: 18,
    buttonShadow: "0 1px 3px rgb(60 56 54 / 0.16)",
    cardPadding: 22,
    cardHeaderHeight: 54,
    menuItemHeight: 38,
    menuItemMargin: 4,
    segmentedPadding: 3,
    tabGutter: 28,
    titleMarginTop: "1.25em",
    titleMarginBottom: "0.55em",
    inputPaddingInline: 12,
    inputPaddingBlock: 5,
  },
  radius: { small: "0.25rem", medium: "0.375rem", large: "0.5rem" },
  shadow: "0 1px 2px rgb(7 54 66 / 0.12)",
  controlHeight: 34,
  status: {
    success: { foreground: "#2b5900", background: "#e2f0d3", seed: "#859900" },
    warning: { foreground: "#6b4700", background: "#f6e29d", seed: "#b58900" },
    danger: { foreground: "#7a1715", background: "#fcdcd7", seed: "#dc322f" },
    info: { foreground: "#004857", background: "#d3f0f7", seed: "#268bd2" },
  },
};
